export const VEXML_VERSION = VITE_VEXML_VERSION;

export const LOCAL_STORAGE_VEXML_SOURCES_KEY = 'vexml:sources';

const LOCAL_STORAGE_SAVED_MUSICXML_KEY = 'vexml:saved_musicxml';
const LOCAL_STORAGE_USE_DEFAULT_MUSICXML_KEY = 'vexml:use_default_musicxml';
export const DEPRECATED_LOCAL_STORAGE_KEYS = [LOCAL_STORAGE_SAVED_MUSICXML_KEY, LOCAL_STORAGE_USE_DEFAULT_MUSICXML_KEY];
