export type Config = {
  DEFAULT_SYSTEM_DISTANCE: number;
  DEFAULT_STAVE_DISTANCE: number;
  TITLE_TOP_PADDING: number;
  TITLE_FONT_FAMILY: string;
  TITLE_FONT_SIZE: string;
  PART_NAME_FONT_SIZE: string;
  PART_NAME_FONT_FAMILY: string;
  VOICE_PADDING: number;
  MEASURE_NUMBER_FONT_SIZE: string;
  MULTI_MEASURE_REST_WIDTH: number;
};

export const DEFAULT_CONFIG: Config = {
  DEFAULT_SYSTEM_DISTANCE: 80,
  DEFAULT_STAVE_DISTANCE: 80,
  TITLE_TOP_PADDING: 40,
  TITLE_FONT_FAMILY: 'Arial',
  TITLE_FONT_SIZE: '36px',
  PART_NAME_FONT_FAMILY: 'Arial',
  PART_NAME_FONT_SIZE: '13px',
  VOICE_PADDING: 80,
  MEASURE_NUMBER_FONT_SIZE: '10px',
  MULTI_MEASURE_REST_WIDTH: 200,
} as const;
