name: test
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  premerge:
    name: run premerge code checks
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22.6.0
          cache: npm
      - name: install
        run: npm ci
      - name: fix
        run: npx vex fix --check
      - name: test
        run: npx vex test --ci
